// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 9/16/2026, 3:03:50 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/app/applet/components/**/*.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","/app/applet/components/global/**/*.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","/app/applet/components/**/*.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","/app/applet/layouts/**/*.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","/app/applet/plugins/**/*.{js,ts,mjs}","/app/applet/composables/**/*.{js,ts,mjs}","/app/applet/utils/**/*.{js,ts,mjs}","/app/applet/pages/**/*.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","/app/applet/{A,a}pp.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","/app/applet/{E,e}rror.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","/app/applet/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;